const movies = [
	{
		Title: 'Dune',
		Year: '2021',
		Rated: 'PG-13',
		Released: '22 Oct 2021',
		Runtime: '155 min',
		Genre: 'Action, Adventure, Drama',
		Director: 'Denis Villeneuve',
		Writer: 'Jon Spaihts, Denis Villeneuve, Eric Roth',
		Actors: 'Timothée Chalamet, Rebecca Ferguson, Zendaya',
		Plot: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
		Language: 'English, Mandarin',
		Country: 'Canada, United States',
		Awards: 'Won 6 Oscars. 158 wins & 262 nominations total',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
		Ratings: [
			{
				Source: 'Internet Movie Database',
				Value: '8.1/10',
			},
			{
				Source: 'Rotten Tomatoes',
				Value: '83%',
			},
			{
				Source: 'Metacritic',
				Value: '74/100',
			},
		],
		Metascore: '74',
		imdbRating: '8.1',
		imdbVotes: '547,113',
		imdbID: 'tt1160419',
		Type: 'movie',
		DVD: '22 Oct 2021',
		BoxOffice: '$108,327,830',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'See',
		Year: '2019–',
		Rated: 'TV-MA',
		Released: '01 Nov 2019',
		Runtime: '60 min',
		Genre: 'Action, Drama, Sci-Fi',
		Director: 'N/A',
		Writer: 'Steven Knight',
		Actors: 'Jason Momoa, Sylvia Hoeks, Hera Hilmar',
		Plot: 'Far in a dystopian future, the human race has lost the sense of sight, and society has had to find new ways to interact, build, hunt, and to survive. All of that is challenged when a set of twins are born with sight.',
		Language: 'English',
		Country: 'United States',
		Awards: '6 wins & 9 nominations',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BM2JkM2Y5NTEtZWIwZS00ZTliLTk3MDMtNzY4MDNkNjg0NTkwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
		Ratings: [
			{
				Source: 'Internet Movie Database',
				Value: '7.7/10',
			},
		],
		Metascore: 'N/A',
		imdbRating: '7.7',
		imdbVotes: '71,176',
		imdbID: 'tt7949218',
		Type: 'series',
		totalSeasons: '2',
		Response: 'True',
	},
	{
		Title: 'Hello',
		Year: '2008',
		Rated: 'N/A',
		Released: '10 Oct 2008',
		Runtime: '129 min',
		Genre: 'Drama, Romance',
		Director: 'Atul Agnihotri',
		Writer: 'Atul Agnihotri, Chetan Bhagat, Jalees Sherwani',
		Actors: 'Sharman Joshi, Amrita Arora, Sohail Khan',
		Plot: 'Call-center workers receive a phone call from God.',
		Language: 'Hindi',
		Country: 'India',
		Awards: '1 nomination',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BZGM5NjliODgtODVlOS00OWZmLWIzYzMtMTI2OWIzMTM1ZGRhXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg',
		Ratings: [
			{
				Source: 'Internet Movie Database',
				Value: '3.3/10',
			},
		],
		Metascore: 'N/A',
		imdbRating: '3.3',
		imdbVotes: '2,132',
		imdbID: 'tt1087856',
		Type: 'movie',
		DVD: '05 Apr 2018',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Killing Anabella',
		Year: '2018',
		Rated: 'N/A',
		Released: '15 Sep 2018',
		Runtime: '13 min',
		Genre: 'Animation, Short',
		Director: 'Aman Bhanot',
		Writer: 'Aman Bhanot',
		Actors: 'N/A',
		Plot: "Revolves around a complex character named Anabella. A girl born in Mexico, with dead parents, a horrific past haunting its way into her life and her only companion 'Lolita' the dog. Being traumatized by a Psycho Killer, Anabella i...",
		Language: 'English',
		Country: 'India',
		Awards: 'N/A',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BZDYzNGU4MTUtZGUxYi00ZjI0LTg3ZTktMWZiYjVlOTc3ZTRhXkEyXkFqcGdeQXVyOTI2OTIzNjc@._V1_SX300.jpg',
		Ratings: [
			{
				Source: 'Internet Movie Database',
				Value: '7.5/10',
			},
		],
		Metascore: 'N/A',
		imdbRating: '7.5',
		imdbVotes: '6',
		imdbID: 'tt9016874',
		Type: 'movie',
		DVD: 'N/A',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Avenger',
		Year: '2006',
		Rated: 'Not Rated',
		Released: '09 Apr 2006',
		Runtime: '92 min',
		Genre: 'Thriller',
		Director: 'Robert Markowitz',
		Writer: 'Alan Sharp (teleplay), Frederick Forsyth (novel)',
		Actors: 'Sam Elliott, Timothy Hutton, James Cromwell, William Hope',
		Plot: 'A C.I.A. Agent steps in to stop a former Special Forces Operative on a for-hire mission that poses a global threat.',
		Language: 'English',
		Country: 'USA',
		Awards: 'N/A',
		Poster:
			'https://m.media-amazon.com/images/M/MV5BMTMzMjMwMjcyNl5BMl5BanBnXkFtZTcwNTA1NDgzMQ@@._V1_SX300.jpg',
		Ratings: [
			{
				Source: 'Internet Movie Database',
				Value: '5.6/10',
			},
		],
		Metascore: 'N/A',
		imdbRating: '5.6',
		imdbVotes: '913',
		imdbID: 'tt0473445',
		Type: 'movie',
		DVD: '03 Oct 2006',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
	{
		Title: 'Tee',
		Year: '2010',
		Rated: 'N/A',
		Released: '01 Oct 2010',
		Runtime: '5 min',
		Genre: 'Short',
		Director: 'Avinash Medhe',
		Writer: 'N/A',
		Actors: 'N/A',
		Plot: 'N/A',
		Language: 'N/A',
		Country: 'India',
		Awards: '1 win.',
		Poster: 'N/A',
		Ratings: [
			{
				Source: 'Internet Movie Database',
				Value: '7.7/10',
			},
		],
		Metascore: 'N/A',
		imdbRating: '7.7',
		imdbVotes: '10',
		imdbID: 'tt2512148',
		Type: 'movie',
		DVD: 'N/A',
		BoxOffice: 'N/A',
		Production: 'N/A',
		Website: 'N/A',
		Response: 'True',
	},
];

const users = [
	{
		id: 123,
		role: 'basic',
		name: 'Basic Thomas',
		username: 'basic-thomas',
		password: 'sR-_pcoow-27-6PAwCD8',
	},
	{
		id: 434,
		role: 'premium',
		name: 'Premium Jim',
		username: 'premium-jim',
		password: 'GBLtTyq3E_UNjFnpo9m6',
	},
];

module.exports = {
	users,
	movies,
};
