env:
  browser: false
  es2021: true
  jest: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended


settings: {
  import/resolver: {
    node: {
      paths: [ 'src' ]
    }
  }
}

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'prettier'
rules: {
  "import/extensions": [
    "error", "ignorePackages", { "ts": "never" }
  ],
  "import/no-unresolved": [2, {commonjs: true, amd: true}],
  "import/no-extraneous-dependencies": [0, {"devDependencies": ["**/*.test.js", "**/*.spec.js"]}],
  "unicorn/consistent-function-scoping": 0,
  "unicorn/filename-case": 0,
  "unicorn/no-nested-ternary": 0,
  "unicorn/prefer-spread": 0,
  "unicorn/no-null": 0,
  "no-unused-vars": "off",
  "no-useless-constructor": "off",
  "no-console": ["error", {allow: [ "warn", "error" ]}],
  "no-empty-function": ["error", {allow: ["constructors"]}],
  "@typescript-eslint/no-unused-vars": ["error"],
  "@typescript-eslint/no-magic-numbers": [ "error" , {
      "ignoreArrayIndexes": true,
      "ignoreDefaultValues": true,
      "ignore": [-1, 0, 1]
  }]
}
overrides:
  - files:
      - "**/*.ts"
