version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    env:
      JWT_SECRET: secret
      MONGO_PROD_URI: "mongodb+srv://movie-api-islam:nodeislam@cluster0.ovd64.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - run:
          command: npm build
          name: Build app
      - persist_to_workspace:
          root: ~/nodejs-recruitment-task
          paths:
            - .

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature-1
                - master
                - main
