version: "3.2"
services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: ../auth-service/Dockerfile
    volumes:
      - ../auth-service:/app/
    environment:
      - NODE_ENV=development

  movies-service:
    build:
      context: ../movies-service
      dockerfile: ../movies-service/Dockerfile
    command: ["yarn", "start:dev"]
    volumes:
      - ../movies-service/app:/app
      - ../movies-service/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ../movies-service/docker/test-entrypoint.sh:/usr/local/bin/test-entrypoint.sh
      - /app/node_modules
    environment:
      - NODE_ENV=development
