version: "3.7"
services:
  auth-service:
    image: auth-service
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - JWT_SECRET
    command: ["node", "./src/server.js"]

  movies-service:
    image: movies-service
    environment:
      - NODE_ENV=production
      - DEBUG_MODE
      - LOG_LEVEL
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - JWT_SECRET
      - AUTH_SERVICE_API_URL
      - OMDB_API_KEY
    ports:
      - "3001:80"
    depends_on:
      db:
        condition: service_healthy
    command: ["yarn", "start:dist"]

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 50
