version: "3.2"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - published: ${POSTGRES_PORT:-5432}
        target: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s    
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-movies}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    volumes:
      - .:/app/
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-movies}
