version: "3.2"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - published: ${POSTGRES_PORT:-5432}
        target: 5432
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    volumes:
      - .:/app/
    depends_on: 
      - "postgres"  
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
