# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run test CI

on:
  push:
    branches: [ master, ft/task-solution ]
  pull_request:
    branches: [ master, ft/task-solution ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{github.workspace}}/../services/movie

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: using node js
      uses: actions/setup-node@v2.1.5
      with: 
        node-version: ${{ matrix.node-version }}
        
    - name: install and test
      run: | 
        pwd
        npm install
        npm test
      env: 
        CI: true
    
      
